### ISSUE TITLE
Any time UI opens or notification, screen goes black

### ISSUE THREAD

**Issue by IMcPwn** [CKProductionsDev/PlayStatus-Issues#2]
Any time the UI opens or I receive a notification, everything except UI is blacked out - I tried disabling "always on top" and that only allows me to see my Windows task bar. I can't see my game or my desktop at all when it is open. Can the black be switched to transparent?

<img width="1919" alt="image" src="https://github.com/CKProductionsDev/PlayStatus-Issues/assets/5580020/37437239-9905-4ce6-9467-d841c980eb50">

**Comment by c0redump3d** [comment]
Hi there, apologies for the delayed response;

This shouldn't be happening, as the black is typically supposed to be rendered as transparent. This could be from a few things:

First, have you tried restarting PlayStatus? If not please try to do so as it will re-attempt to make the window transparent. There is an extremely slight chance that the window transparency might fail, or an issue with DWM (a Windows API that allows for transparent windows), in which case a full computer restart may be necessary.

Could you try these two things if you haven't, and let me know if this is still happening. If it is, could you give me a little more information about your computer, like the Windows version you're running (it seems like Windows 11, but make sure it's updated), and also you're GPU (if it's nvidia or amd)

**Comment by IMcPwn** [comment]
Hello - no worries. I attempted restarting the app a few times and restarting my PC to rule those out.

I am running Windows 11 Pro 23H2 22631.3593. I have an AMD GPU. I have an HDR display that is calibrated. Happy to provide any other info that may be necessary.

**Comment by c0redump3d** [comment]
Darn, this is really weird. I'm sure you've probably already checked this, but also see if you have any GPU updates, as I see there were some issues with transparency effects on Windows 11 a while back on them.

Could you also check in Windows Settings, under System -> Display -> Graphics (all the way at the bottom of the page) -> Change Default Graphics Settings. Do you have Hardware-accelerated GPU scheduling enabled and Optimizations for windowed games enabled? I think the latter is forced on if you're using HDR.

Could you also attach a log file, which you can find by pressign Win + R and entering %localappdata%\CKProductions\PlayStatus\Logs

**Comment by c0redump3d** [comment]
Also make sure you have transparency effects enabled under Personalization -> Colors.
If you've disabled animations in Windows, try this; Press Windows Key + R type in SystemPropertiesPerformance.exe and hit enter, and if custom is selected, could you try setting it to 'Let Windows Decide' and see if it does anything?

**Comment by IMcPwn** [comment]
Sorry I missed your quick reply - I must not have email notifications on. I checked GPU updates - no updates. These two were both on- Hardware-accelerated GPU scheduling enabled and Optimizations for windowed games enabled.

Transparency effects were enabled under Personalization -> Colors

I was not at the default animations, I set it to "Let Windows Decide" but still black screen after opening the app (it was closed before testing).

Here are the logs-

[app_2024-05-31_00-40-50.log](https://github.com/user-attachments/files/15519138/app_2024-05-31_00-40-50.log)
[app_2024-05-31_18-12-23.log](https://github.com/user-attachments/files/15519139/app_2024-05-31_18-12-23.log)
[app_2024-05-31_00-19-55.log](https://github.com/user-attachments/files/15519140/app_2024-05-31_00-19-55.log)
[app_2024-05-31_00-20-14.log](https://github.com/user-attachments/files/15519141/app_2024-05-31_00-20-14.log)
[app_2024-05-31_00-29-07.log](https://github.com/user-attachments/files/15519142/app_2024-05-31_00-29-07.log)

**Comment by c0redump3d** [comment]
Okay -- I just pushed out a small update through Steam, version 3.6.2. Could you please update and see if the issue may be resolved? There was a slight oversight with a color profile that might've been being incorrectly applied, which might potentially of caused it on specific systems. I also added more debugging information/handling when applying the transparency, which if it still is erroring out, a new log should hopefully provide more information!

**Comment by IMcPwn** [comment]
Thank you for the quick patch! Unfortunately issue still persists but here are the new logs-

[app_2024-05-31_19-49-30.log](https://github.com/user-attachments/files/15519520/app_2024-05-31_19-49-30.log)
[app_2024-05-31_00-40-50.log](https://github.com/user-attachments/files/15519521/app_2024-05-31_00-40-50.log)
[app_2024-05-31_18-12-23.log](https://github.com/user-attachments/files/15519522/app_2024-05-31_18-12-23.log)

**Comment by c0redump3d** [comment]
Wow, this is so weird; even Windows is reporting a success message when setting the window to transparent. I've just pushed a second update out and changed some things around, could you please check if it does anything?

If not, then it almost certainly isn't a bug with PlayStatus, since the process of making a transparent window is very well documented and straight-forward. I'm going to keep looking around and see if there is any other things I can attempt to change, but it's pretty difficult since Windows isn't helping and just reporting a success and I cannot seem to reproduce it on my end D:.

**Comment by IMcPwn** [comment]
So weird that it still isn't working - I tried rebooting, disabling and re-enabling transparency in Windows but it still doesn't work. Would you be willing to say which transparency method/library you use so I can test it myself with various configurations and let you know the findings?

**Comment by IMcPwn** [comment]
I did some reading and it appears to be similar to this - still researching https://github.com/electron/electron/issues/40515

**Comment by IMcPwn** [comment]
I figured something out - when I disable HDR on Windows, the app works as expected. _If I re-enable HDR it continues to work until reboot._ **this appears to be false after further testing**

I think I'll still keep your app because you seem like a great developer and I think it's worth it for the great functionality you've implemented but I'd love to see HDR support!

**Comment by c0redump3d** [comment]
See the odd thing is that I also use HDR on my monitors and works totally fine 😵‍💫. It may have to do with AMD and HDR particularly... I am super sorry that none of this seems to have solved it, but I assure you I'll continue to look into it and see if I can't fix it.

Also, PlayStatus uses a native Windows DWM (Desktop Window Manager) API call, `DwmExtendFrameIntoClientArea` to create a transparent window for reference.

**Comment by c0redump3d** [comment]
I'd check Auto HDR settings, and any HDR calibration profiles you may have created? These could be possibly affecting how it shows transparency.

**Comment by IMcPwn** [comment]
That's convenient you're using HDR as well, no worries, I'm glad we're making progress, here is my color profile I created using the [Windows HDR Calibration tool](https://apps.microsoft.com/detail/9n7f2sm5d1lr?rtc=1&hl=en-us&gl=US) from Microsoft to get peak brightness correctly set in game. I am using Auto HDR enabled.

[HDR Calibrated Profile 2-29-2024 22917.zip](https://github.com/user-attachments/files/15520241/HDR.Calibrated.Profile.2-29-2024.22917.zip)

**Comment by IMcPwn** [comment]
In the logs I noticed the resolution stated (1922x1080) does not match my display's resolution: 3840 x 2160. Not sure if that is related

"Resized to 3840x2160, new desired dimensions are 1922x1080"

**Comment by c0redump3d** [comment]
Nope, that's fine since the UI is always scaled to 1920x1080 (just makes it so UI controls and menus stay consistent across multiple resolutions and scale factors).

I don't think it would be the color profile you have, but if you could, try using the default color profile and see if anything changes.

Maybe also try and take a look around in the AMD radeon settings, and see if there are any options relating to HDR, or color depth; and see if changing any of those options yields anything.

I have some ideas I can take a look at tomorrow.

**Comment by IMcPwn** [comment]
Looks like the color profile didn't have any effect - I'm using the AMD driver in "driver mode" so it has no Radeon settings or app that I can find
